### ISSUE TITLE
howler takes time to play audio on safari

### ISSUE THREAD

**Issue by ajitkhatke** [goldfire/howler.js#1172]
when i load the page and click a button to play audio. it takes 10 sec to play audio. every time it takes time to play. even if i stop audio and play it again. it still takes time to play audio. desparately need to cut this waiting time. 
note: This issue is occured on ios.

**Comment by alexhackney** [comment]
I have the same issue with streaming audio in any browser. Page loads and is ready to play. I hit play and it buffers up 9-10 seconds before I hear audio. Not sure why this is happening?

**Comment by goldfire** [comment]
Please provide a code sample.

**Comment by Joshfindit** [comment]
Is there a chance that this is a bandwidth/latency problem?

**Comment by alexhackney** [comment]
@ajitkhatke Did you solve your issue?

**Comment by ajitkhatke** [comment]
not really ..just fixed it with a patch of code. can't say it solved.

**Comment by alexhackney** [comment]
Care to share what you did? I'm still having the issue. When you load the page and click play it loads for almost 10secs before audio plays.

**Comment by ajitkhatke** [comment]
i used audio.js. you can try it if you want.

**Comment by pahund** [comment]
As far as I can see, this is a limitation of the web audio API (HTML5). When you use it to play a stream of encoded audio, the browser always buffers the audio for some seconds. I've been trying to find a way around this for days. I know Spotify and SoundCloud can pull of low-latency audio streaming, but how, I cannot tell.

**Comment by alexhackney** [comment]
I think one thing they probably do is not use mp3. I've noticed aac streams
load much faster.

**Comment by pahund** [comment]
@alexhackney 

That goes without saying, you need to stream a compressed format like mp3 or ogg. With [my current project](https://github.com/pahund/zapperment), I succeeded in getting a low latency stream going with uncompressed wav format, but the server could not handle more than one or two concurrent clients. So now I'm using Howler.js, streaming mp3. Latency is around 5 seconds. I'm trying to work around that instead of trying to fix it now.

**Comment by st-h** [comment]
the last time I looked, I got the impression that Soundcloud manages its own streaming implementation, as they split their files into small mp3 chunks (each about 10 seconds long). You can easily check by opening the network inspector before playing a file. I was just a little surprised that it actually seem to be mp3 files, as I read that they moved to opus a while ago.

**Comment by pahund** [comment]
@st-h yeah, that's what I suspect, too. I tried to go down that way, and then realized it's going to be way too much effort for a 1-man-team to pull this off.

**Comment by st-h** [comment]
@pahund hmm, I came across [phonograph](https://gitlab.com/Rich-Harris/phonograph) a while ago. I have not tried it so far, but that could probably help. Please let me know how it goes in case you try it. Then there is always the possibility to leverage service workers and opus to [implement streaming and decoding yourself](https://blog.mixanalog.com/how-to-stream-lossless-audio-in-safari) - but, this will likely not be much less work than using little mp3 chunks. I think this currently is quite an unsatisfactory situation, as by the time we are talking about iOS there is no alternative, as other browser just have to use the same buggy engine as safari. If they at least would support Audio Worklets ... or just start to read their bug reports...

**Comment by alexhackney** [comment]
@pahund aac is compressed. Did you try it?

**Comment by pahund** [comment]
@alexhackney No, haven't tried it, but I doubt it will help.

The problem is that to get low-latency audio to play, you use can use the Web Audio API's [decodeAudioData](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData) method, but this is only meant to be used with complete tracks, not with streams, quote:

> This method only works on complete file data, not fragments of audio file data

I managed to get this to work with an unencoded PCM stream by added a wav header to every chunk of the stream, as [described here](https://apiko.com/blog/audio-file-streaming-in-js/).

I thought, naïvely, “OK, I can just create an mp3 stream and add an mp3 header to every chunk then”, but that's not how mp3 works.

**Comment by alexhackney** [comment]
@pahund As someone who manages streaming for 9 terrestrial stations, I can tell you aac is better for low latency streaming. The buffering that the browser does for mp3 takes longer. Just using aac makes everything faster.

I would also look at Amplitude.js

**Comment by pahund** [comment]
@alexhackney I've tried your suggestions:

* using Amplitude.js, seems to be a better choice for streaming than Howler.js, because it supports pausing a stream, thanks for the tip!
* using AAC – sadly, the latency is even worse, it now takes more than a minute for my live audio to be played by the browser

To see if the problem is with my software, I've tried using FFmpeg, sending a stream to an Icecast server, the delay is still the same, more than 60 sec.

I'm using this command to create the AAC stream with FFmpeg:

´´´
ffmpeg -f avfoundation -i "none:4" -c:a aac -content_type 'audio/aac' -vn  icecast://source:MY_SECRET_PASSWORD@localhost:8000/stream.aac
´´´

Perhaps you have a tip for me for tweaking the the AAC encoder to make it more efficient? I'm still very new at all this stuff and have a hard time making sense of all the FFmpeg options.

**Comment by pahund** [comment]
@st-h I've looked at phonograph, but it looks like it doesn't support live streams, and it doesn't work on Firefox, which is a no-go for me

**Comment by xerosanyam** [comment]
lots of good recommendations here:
- amplitudejs
for most people who just want to play audio in ios reliably, I think howlerjs is better than amplitude.
I tried playing the demo of amplitudejs: `https://521dimensions.com/open-source/amplitudejs`.. it doesn't play reliably in safari desktop(ios would be worse), however, howlerjs demo was working each time(after refreshing the page).

- aac over mp3
WIP(will update soon)
