### ISSUE TITLE
Aw Snap! In mobile Android

### ISSUE THREAD

**Issue by adrianovcar** [goldfire/howler.js#1185]
What I need: Mute and unmute tracks from a song. 

I have 10 mp3 files that represents an instrument from a song. So I have all channels from a song separately.

When howler load these 10 mp3 files (already tried many other formats and codecs), everything seems to be ok, but when the "loaded" event is hired, the chrome crash and I get a fatal error screen (white aw snap!).

The problem seems occur after the file is loaded and howler prepare it to be ready to play.
It doesn't happen on Desktop and iOS, only on Android (I have tested android 6 to 9)

Yes, I had tried use sprites too. The mp3 file was about 30 minutes and the crash happened.

If I set HTML5 to TRUE, everything is fine but with  'audio' element, the tracks are out of sync, and the music stay out of compass.

My mp3 files are about 1mb each and each song I have, has about 7 tracks/instruments.

**How reproduce this error:** 

_Using Sprite (with audiosprite)_
[https://stage.kovverapp.com/goldfire/howler/146](https://stage.kovverapp.com/goldfire/howler/146)
[https://stage.kovverapp.com/goldfire/howler/156](https://stage.kovverapp.com/goldfire/howler/156)

_Without sprites, instancing 10 elements at same time:_
[https://stage.kovverapp.com/goldfire/howler/116](https://stage.kovverapp.com/goldfire/howler/116)

**Some considerations:**

- I can't use simple audio element because sometimes it can't keep the tracks synched, I already tried everything with no success, my only chance is with webaudio;
- I saw other issues about chrome crash but I think this case is different, can be associated  with memory limits or process performance (I don't know);
- This page will be embed in an app (with React Native), but the behaviour is the same for testing purposes,  you can test on your mobile chrome as well;

**Comment by ogelacinyc** [comment]
It same to me. 
But in my case it causes only iphone device and chrome and safari.
I have 18 mp3 files, 16MB, 14 minutes.

**Comment by st-h** [comment]
The problem with longer mp3 files is that a audio source buffer is used to decode the file, which keeps the whole decoded data in memory (which usually is quite large). (I think the reasoning behind this is that this technology has been designed to be used with short sprites for games etc.) I have seen the error you describe when the browser runs out of memory (or thinks it would be wise to limit the memory) - however its kinda unusual to me that it does not appear on iOS. (safari on desktop usually shows a pretty annoying warning as soon as a page uses significant amounts of memory)

If you set html5 to true, howler internally uses an audio element for playback, which is designed to stream the data from your server (instead of keeping everything in memory). This works great with longer files (unless you run into one of apples edge cases), however there currently is no way I am aware of to efficiently sync multiple tracks this way with good precision. There is an MDN page somewhere which mentions audio worklet as a workaround, however safari still does not support it. So, unfortunately there is nothing I could recommend which just would work out of the box.
