### ISSUE TITLE
fade not working on iOS

### ISSUE THREAD

**Issue by mdedwards** [goldfire/howler.js#1237]
Hello, fade in/out is not working on my iPAD with 12.4.1 when using html5. I can hear this when running the core tests. It's working on OSX and Android though. Best, Michael

**Comment by ecoconso** [comment]
Same problem here, on iPad Air 2 running iOS 12.3.1, using html5 as well, with sprites.
Fading is not working - volume setting neither. I guess it is a volume related problem.
I mention thats sounds are triggered from a user action on a button, as this is the only option on iPad.
... Any idea or workaround to this ?

**Comment by ecoconso** [comment]
ok... setting html5 to false made the trick.

**Comment by mishawagon** [comment]
But setting html5 to false to fix this is not ideal. My sound doesn't stream on android unless I set html5 to true. I guess I'm gonna write my own fade with set intervals.

**Comment by mishawagon** [comment]
Well that didn't fix it as i'm still calling .volume a lot, and that doesn't work in iOS apparently:
https://github.com/goldfire/howler.js/issues/805

**Comment by soloetra** [comment]
Hello! On iPad and iPhone Fade is not working with HTML5 enabled. 

If you  disable HTML5, then fade will work, but odd distortion begins to happen as long as volume is changing.
I tried with different sound samples:  samples at 44.1 and 48kHz, mp3 and wav. All of them sound crackled  while fading in iPad or iPhone with HTML5 disabled.

Has anyone found any hack to make fade work with HTML5 enabled?
Or maybe a way to fade without the distortion when not using HTML5?

I'd appreciate any help, since fading is critical on my project.

Thank you!!!

**Comment by shreyas-jadhav** [comment]
any updates? workarounds? disabling `html5` is not a really good option for me.

**Comment by goldfire** [comment]
It is not possible to change the volume with anything but the physical volume buttons on iOS when using HTML5 audio. There is no workaround possible. This is outlined in the [Apple docs](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html).
