### ISSUE TITLE
How to create seamless loop?

### ISSUE THREAD

**Issue by TheManFromEarth1** [goldfire/howler.js#1426]
Right now when I loop, it stops for a second and then starts again.

I used the example with slight changes:
https://gist.github.com/TheManFromEarth1/896d429e8c3176b56be7a0b37b0c4b20

`  sound = data.howl = new Howl({
        src: ['./audio/' + data.file + '.mp3',  './audio/' + data.file + '.wav'], 
        html5: true, 

        onplay: function() {
          // Start the wave animation if we have already loaded
          wave.container.style.display = 'block';
          bar.style.display = 'none';
          pauseBtn.style.display = 'block';

          sound.fade(1,1, 2000) **// Tried fade, can't use it here**
          self.loop; **// Added loop here**
        },`

**Comment by TheManFromEarth1** [comment]
1st problem: Mp3 files always have empty noise at the beginning or end, so it seems like it's stopping when it's not.
Solution: Don't use MP3 or create a custom script with fade/buffer or something.

2nd problem: Even after removing MP3's, there still was a small delay when restarting a loop.
Not sure what exactly fixed it, but now it works. One of the changes was I use the minified version now.

**Comment by st3v0** [comment]
This is actually a problem in the LAME MP3 Decoder which browsers use. The decoder adds padding to the head & tail. If you look at the raw binary of an mp3 there is no padding. You can visually see this by loading an mp3 using Audacity. Audacity uses the same decoder as browsers. If you use a different tool like Adobe Audition you will not see the padding, this is because Audition uses a different MP3 Decoder.

You are correct in your solution if you use a different format like WAV there will be no extra padding added when it's decoded by the browser. Unfortunately WAV is uncompressed and will be very large.

However it is still possible to use MP3 if you don't need the loop to be perfect. You can use the sound sprite controls and configure an offset and duration within the loaded sound. The offset and duration can be calculated using Audacity. This essentially tells howler to not play the sound from beginning to end but instead play if from the offset position for a duration, essentially skipping the padding which is added by the decoder.

**Comment by ProgrammingLife** [comment]
Maybe you wanna use webm for that?

**Comment by wmonecke** [comment]
@st3v0 I used a .wav file to test if this was true but I can still hear the gap. I edited in Audacity and made sure there were no gaps at the star or end of the file.

Any ideas?

**Comment by st3v0** [comment]
Hmm very strange. In all my past testing wav files worked fine. It’s been a while now since i last looked at this. The only other thing i can think of ATM would be; maybe the sound engine is going to sleep between repeats. I remember that was previously a thing. The fix at the time was to have the sound engine play a continuous empty sound stream by feeding raw bytes into the sound buffer. That would force the sound engine to stay awake.  But we havn’t needed to do that for a long time.

Unfortunately that's all I got at the moment, I have not worked with howler or audio for like 3yrs now so I can’t  really be much more help, sorry.
