### ISSUE TITLE
Volume changes will not apply on IOS

### ISSUE THREAD

**Issue by maxstewartsteele** [goldfire/howler.js#1507]
I have been trying to create a simple mixer that can have 4 different sounds playing at once, with volume sliders to adjust them.
This is the way each of the sounds is set up, with a slider assigned to adjust the volume. It works fine on desktop and android, and online it said setting html5 to false would fix it on IOS but that has not been the case. I have checked and the internal volume attribute is being changed, however, the actual playback volume does not change.

`var p = new Howl({
  	src: [("s/" + e[1])],
  	loop: false,
  	volume: 0.0,
	html5: false,
});`

**Comment by shreyas-jadhav** [comment]
any updates / workarounds on this?

**Comment by luckydonald** [comment]
That's how iOS works. The two buttons on the side dictate the volume setting.

**Comment by goldfire** [comment]
I've double-checked this and nothing has changed on this front. When html5 is set to false (FYI, that is the default, so no need to set it explicitly), then the volume can be controlled. This works fine on an iPhone with the Web Audio Tests on howlerjs.com. If you've got a scenario where that isn't working, I would need a full test case rather than just the setup.
