### ISSUE TITLE
Sound delayed when using AirPods

### ISSUE THREAD

**Issue by Miodec** [goldfire/howler.js#1531]
Hey, I'm testing using AirPods and just built-in speakers, and the AirPods are noticeably delayed. It happens in any browser. I feel like this might be exclusive to Apple devices as they do some voodoo magic to sync the audio. Any ideas on how to fix this?

**Comment by Friksel** [comment]
Hi, I am not the developer of howler, but I just saw this item and feel free to react.

Delays in AirPods have nothing to do with Howler. Howler doesn't do the underlying technique to play audio either, that's built into the browser and device.

AirPods are blue tooth so most probably the issue is just that: bluetooth needs time to process and send the signal.
