### ISSUE TITLE
Audio files not loading correctly

### ISSUE THREAD

**Issue by joelboersma** [goldfire/howler.js#1537]
Hey all, I'm making an app with React and TypeScript and want to use Howler for sounds. I'm trying to instantiate a `Howl` that will be played when the user clicks a button. Below is a code snippet from my `App.tsx`:

```Typescript

Howler.autoUnlock = true

const App: FC = () => {
  const myHowl= new Howl({
    src: 'example.mp3',
    preload: true,
    html5: true,
    onloaderror: (id: number, e: any) => {
      console.error(`Howl load error: ${e}`);
    }
  });

  const playSound = () => {
    myHowl.play()
  }
  
  return (
    <div className="App">
      <button id="Play" onClick={playSound}>Play</button>
    </div>
  );
}
```

I keep getting errors when trying to load my sound file.
- When `html5` is set to `true`, I get a `4` error code, [meaning my media resource is "not suitable"](https://html.spec.whatwg.org/multipage/media.html#mediaerror).
- When `html5` is set to `false`, I get "Decoding audio data failed" for an error.
 
My `App.tsx` and `example.mp3` are in the same directory. I have also tried using different mp3 files. And yes, when I open them in a media player, they play just fine.

Any help is appreciated. Thank you!

**Comment by Johoseph** [comment]
The issue you're running into here is due to the way React/webpack bundles static assets - in this case React doesn't know where to find 'example.mp3'.

To fix this, you can import your mp3 and use the imported variable instead (exactly the same way you would import and use a [static image](https://create-react-app.dev/docs/adding-images-fonts-and-files/)):
```
import example from "/example.mp3"; // Relative path to media
```

... and then when instantiating your `Howl` instance:

```
  const myHowl = new Howl({
    src: example,
    preload: true,
    html5: true,
  });
```

Typescript will likely complain about missing type declarations for `.mp3` files, you can fix this by adding a declaring a new type module within a `.d.ts` file like this:
```
declare module "*.mp3" {
  const value: string;
  export default value;
}
```

**Comment by joelboersma** [comment]
Thank you for your help. I'm a webpack noob.

Once the new `*.mp3` type module was placed in my `Types` directory, I also needed to add it to `typeRoots` in `tsconfig.json`:
```json
"typeRoots": [
  "node_modules/@types",
  "src/Types/"
] 
```

Once I completed a few more (project-specific) steps, I was able to get everything to work as expected.
