### ISSUE TITLE
Feature request: playing multiple audios as a playlist

### ISSUE THREAD

**Issue by hugolpz** [goldfire/howler.js#191]
Maybe I missed something, but I didn't found an easy way to play a list of audios as a playlist. A built-in way to play list of audio files would be helpful. When provided an array of urls corresponding to as many audio files, this function would play these files as a playlist [one at the end of an other] in the same order as the provided array of urls.

----

**Current:** For now, the current way I play a list of audios is a very dirty, not-scalable, hardcoded cascade of howler `play()` + `onend: function(){ ... }` such:

```
var sound = new Howl({
  urls: ['sound_1.mp3'],
  autoplay: true,
  onend: function() {
   ...
  }
}).play();
```

Such, for 3 files : 

```
var sound = new Howl({
  urls: ['sound_1.mp3'],
  autoplay: true,
  onend: function() {
     var sound = new Howl({
     urls: ['sound_2.mp3'],
     autoplay: true,
     onend: function() {
             var sound = new Howl({
             urls: ['sound_3.mp3'],
             autoplay: true,
             onend: function() {
                   // Continue the cascade if more files ares needed.
                }
             }).play();
     }
    }).play();
  }
}).play();
```

**Comment by jayknowstheway** [comment]
Dear Goldfire, the main problem with Howler.JS is that the documentation is not comprehensive. The power and potential of Howler is lost in trying to stay as simple and clean as possible. For me, the basic starting point is precisely the music player idea, for which there are very few articles. To understand how to use holwer, it seemed like learning javascript, instead of easily being able to build a module based on your tool. Would you recommend any resources, examples, or source code that pushes Howler at a higher level, or would you consider expanding the examples of Howler in a comprehensive, real-life situation way? This post was hinting at that before it was closed.

**Comment by goldfire** [comment]
As part of the 2.0 release I plan on creating a wider range of examples. Beyond examples, the docs have been improved in the 2.0 branch, but I'm happy to hear suggestions for areas of the documentation that could still be made more clear.

**Comment by jayknowstheway** [comment]
Goldfire! By the way, thank you for such a cool tool! I see Howler docs as being more than just an API type library. When I imagine examples in the docs, I imagine seeing code for how to make a library of audio tracks, another that has sounds/tracks with dedicated buttons (like a sampler), another showing playback controls. Sounds like a job for the Howler community, as these examples sort of veer into javascript instead of Howler's basics. But maybe you might already have some in the works to further spur development? Thank you for listening!

**Comment by goldfire** [comment]
Thanks for the ideas, I've added this to the 2.0 milestone for docs.

**Comment by goldfire** [comment]
This is now being tracked in https://github.com/goldfire/howler.js/issues/444, so I'm going to go ahead and close this.

**Comment by brydavis** [comment]
```js
var list = [
    'https://example.com/hello.mp3',
    'https://example.com/world.mp3',
    'https://example.com/music.mp3'
]


function autoplay(i, list) {
    var sound = new Howl({
        src: [list[i]],
        preload: true,
        onend: function () {
            if ((i + 1) == list.length) {
                autoplay(0, list)
            } else {
                autoplay(i + 1, list)
            }
        }
    })
    sound.play();
}

autoplay(0, list)
```

**Comment by hugolpz** [comment]
A variation adding the number of loops wanted for the playlist : https://jsfiddle.net/2syojed6/2/
