### ISSUE TITLE
[2.0] Issues with faded (or maybe issue with volume)

### ISSUE THREAD

**Issue by wmodes** [goldfire/howler.js#296]
As I understand it, calling fade triggers the "faded" callback once at the end of the fade. It doesn't pause the audio, so I'm trying to create a handler that does.

    ambientSound = {};

    function setAmbientAudio(ambientAudio) {
    ...
      ambientSound.on("faded", function() { 
        console.log("Ambient sound: ambientSound._volume = "+ambientSound._volume);
        console.log("Ambient sound: ambientSound.volume() = "+ambientSound.volume());
        if (!ambientSound.volume()) {
          ambientSound.pause() 
        }
      });
    }

Much to my surprise when I fade the sound like this:

        ambientSound.fade(ambientSound.volume(), 0, ambientFadeTime);

the callback reports the volume is not zero, but the original pre-faded value. It seems like fade never updates the reported volume value.

    Ambient sound: self._volume = 0.75
    Ambient sound: ambientSound.volume() = 0.75
 
Am I not understanding something?

Since the callback has been removed from the fade function in 2.0.0, how do I pause the audio after fade?  Is there a more reliable way to get the up-to-the-second volume?

**Comment by wmodes** [comment]
Realizing this is can be solved by using the optional ID parameter, but is that intended behavior?

**Comment by goldfire** [comment]
Yes, that is the intended behavior. Each sound that you play can have its own properties, which means it has its own volume that is separate from the Howl (group) volume. If you fade the whole group, then calling `sound.volume()` without the id would give the correct volume, but otherwise you need to pass the soundId in to get the volume for that sound and to pause that sound.
