### ISSUE TITLE
Audio doesn't play after extended idle period

### ISSUE THREAD

**Issue by jtwalters** [goldfire/howler.js#371]
In Google Chrome after several idle hours the audio will no longer `.play()`. Perhaps there's some kind of idle timeout on the AudioContext and it should be re-created if it's no longer available?

**Comment by andreagentili** [comment]
+1, I experienced the same issue. Nevertheless, onend event fires correctly while sound is muted.

**Comment by goldfire** [comment]
Any idea how long you have to leave it idle to reproduce this?

**Comment by jtwalters** [comment]
I would guess an hour.

**Comment by olliep3** [comment]
We're having a similar problem in our game, but for us it seems like you don't necessarily have to leave it idle, it can still happen after 20 or 30 minutes of active play. We have a few pieces of background music in the game and lots of sound effects. Eventually, when switching to one of the tunes, as will have been done several times already in the game, all of the music will disappear completely, yet the sound effects remain, and with no errors.

We initially used a different Howl for each individual sound/music at the start, and just reused them whenever we wanted to play that particular sound. Now, we're creating a new howl at the start of each level for each piece of music, to hopefully refresh them so they won't get stuck, but the problem still occurs. It's odd that it only happens to all of the pieces of music though and not the sound effects, and even when you just choose to play just one of the tunes.

We've only found this behaviour in Chrome so far, 46.0.2490, latest.

**Comment by goldfire** [comment]
I don't suppose any of you have seen any errors from this? Also, are you seeing this strictly with 1.x, 2.0 or both?

@olliep3 Can you tell me some more about your implementation? We have a large number of players that play CasinoRPG for many hours on end and haven't seen this issue. We have a large number of sound effects and music playing with multiple Howls.

**Comment by olliep3** [comment]
Thanks for responding. No, there are no errors unfortunately, and we've only used version 1.1.28.

At the beginning of the project we run through our sound files and create a new Howl for each one as so:

var howl = new Howl( { urls:url, volume:1.0, loop:false, autoplay:false } );

Stored in an array in our sound manager, we then play these howls as and when we need them, originally we didn't create any more new howls after that initial load. We play simply using the play() function after setting parameters on the howl such as loop() and volume() although I don't think we ever change the latter. We don't use sound sprites, each sound is individual.

As I say, sound effects, we haven't had a problem with, but sometimes after around half an hour (though this can vary a lot, it's no one event, it seems, but it's usually at least that amount of time), all of the looping music tracks will stop and not play again. This usually happens when you trigger a new one to play, but I believe it's also been found to just stop a track while it's playing and the game has been left idle. Then, none of the music will play at all after that, yet the sound effects will. We're not loading or storing the music howls any differently, they're loaded in exactly as above.

We then decided to try removing just the music howls each time a new level is started, and reload the tracks in all as new howls, adding them back into the array, but the problem doesn't really change. The sounds don't necessarily stop at the start of a new level.

**Comment by goldfire** [comment]
Has anyone checked to see if `currentTime` on `Howler.ctx` continues to increment or not when this issue occurs? I've been testing a similar issue that happens much faster on Chrome for Android and I believe I've found a solution, but still not sure if it is the same issue that we are seeing here. I reference it in #315.

**Comment by olliep3** [comment]
I don't believe we have, but I will try to find out if it does within the next day or so. Will let you know.

**Comment by olliep3** [comment]
Can confirm that currentTime on Howler.ctx does continue to increment.

I'll try to leave it open in a browser window in case you want me to check anything else too. Just let me know.

**Comment by goldfire** [comment]
@olliep3 Can you try running the following in the console to see if it gets it working again?

    Howler.ctx.suspend();
    Howler.ctx.resume();

**Comment by olliep3** [comment]
No, that doesn't work I'm afraid.

**Comment by goldfire** [comment]
I don't suppose anyone has seen in change in this since beta5 was released? I'm still having trouble reproducing this, which is making it rather tricky to pin down.

**Comment by goldfire** [comment]
I've been testing this extensively with 2.0.0-beta7 on Chrome 47.0.2526.111 and haven't been able to reproduce both when leaving the page idle for 1+ hours and having music playing periodically multiple times over 1+ hour. If anyone is still able to reproduce this I'll reopen.

**Comment by lee-reinhardt** [comment]
@goldfire Sadly I'm getting reports from users that this problem is still happening. The problem certainly seems related to long idle periods between playing files. I was using 2.0 beta7 when it was initially reported. We updated to beta8 and also added `webm` files for compatibility, but it's still happening.

In our app we only have two audio files played as notification alerts. They are both initialized like this:

```
var self = this;
this.audio1 = new howler.Howl({
    src:    ['/audio/audio1.webm', '/audio/audio1.mp3'],
    loop:   true,
    volume: 1.0,
    onstop: function (id) {
        self.audio1.seek(0, id);
    },
});
```

Then, we call `this.audio1.play();` or `this.audio1.stop();` when appropriate. I've been able to gather console logs from users which all indicate the audio should have been playing, but they report not hearing anything. A simple page refresh fixes the issue.

So far it's only been reported by users on Windows 7 and 10 using the latest or near-latest versions of Chrome. I share your frustration with testing it.. very hard to pin down.

My next stop-gap fix I think I'll try is to re-initialize the Howler object every time the sound(s) need to be played and destroy it when stopping. It's heavy-handed but we don't play audio very often.

**Comment by jtwalters** [comment]
This seems related: 
https://bugs.chromium.org/p/chromium/issues/detail?id=518863

**Comment by jamesarm97** [comment]
Was this ever solved? I am seeing the same behavior on Chromium on a raspberry pi and on Safari on a Mac. Sound plays ok for a while then stops. I do hear the speaker make a blip like it tries to play but that is is.

**Comment by aloiseau17** [comment]
Hello, any news about this issue. Still facing it on version 2.2.3.
Is it related to to chrome ? @jamesarm97  seems having the issue on Safari too.

@lee-reinhardt does it solve the issue to recreate an howler instance on each sound ?

**Comment by BoazKG93** [comment]
I still have this issue on 2.2.4, anyone was able to solve it?
