### ISSUE TITLE
Can looping be seamless?

### ISSUE THREAD

**Issue by arxpoetica** [goldfire/howler.js#39]
This is a browser issue, not a library issue, but it would be a real nice-to-have. Check out this loop: http://jsfiddle.net/qyXtT/1/

There's a slight gap between end and start on loop. Is there any way to fix that? It's especially bad for the more ambient sounds, like this rain file, or ambient music. Cross fade?

To add to the note about it being a browser issue, I searched the Chromium dev for an issue, couldn't find one. I might open one; looping should be seamless (same for video). But browsers do a slight pause-gap. Tsk, tsk.

**Comment by tdurand** [comment]
Hi there, 

Is there a way with the library 2.0-beta to cross-fade on loop ? 

Thanks for the amazing work.

**Comment by javismiles** [comment]
Good day, i created a series of seamless loops, that play perfectly seamless in Adobe Audition but when on the web with your wonderful library and the browsers, a terrible gap appears, check here:

http://torchprinciple.com/looptest/test.html

and the code

	  var mysound = new Howl({
	  urls: ["atmosphere-loop-mono-1.mp3"],
  	  volume: 1,
	  loop:1,
	  buffer: false,
  	  onend: function() {
  		},
  	  onplay: function() {},
	  onload: function() {
		  console.log ("loaded");
	  }
		
	});

mysound.play();

how can i solve this? i need seamless loops, and im using your library which should be using web audio api which should work
thanks so much :)

**Comment by petermakowski** [comment]
Hey, @goldfire. Love your Library. I'm still having the problem with both v1 and v2 of Howler.js (works fine only in Safari).

Personally I think you should reopen the the issue (ideally we want it fixed in each browser, but until then howler.js is useless in cases where you need seemles loops). Thank you!

Looping implemented here with Web Audio API works perfectly in the newest Chrome, Firefox and Safari: https://forestmist.org/share/web-audio-api-demo
