### ISSUE TITLE
[2.0 Beta] Still no seamless audio loops?

### ISSUE THREAD

**Issue by Zippy1970** [goldfire/howler.js#421]
I'm still unable to play seamless audio loops with v2.0beta... I've tried both:

```javascript
var audio = new Howl( { 
  src: ['sounds/intro.ogg'],
  loop: true
} );
audio.play();
```
and

```javascript
var audio = new Howl( { 
  src: ['sounds/intro.ogg'],
  sprite: {
    main: [0, 27429, true]
  }
} );
audio.play( "main" );
```

Note that the audio clip I'm playing is 27,429ms in length.

In both cases looping isn't anywhere near seamless. In the first case (without using sprites), there seems to be a 1 second delay before it loops. In the second case (using sprites), there's also a delay but random in duration with each pass.

So am I doing something wrong?

**Comment by goldfire** [comment]
What OS and browser are you seeing this in? I setup a test exactly like what you have (including a 27429ms length audio file) and was not able to reproduce this issue in Chrome, Firefox or Safari. Here's the test I setup:

https://jsfiddle.net/goldfire/yxvz79n9/

**Comment by Zippy1970** [comment]
I'm using howler.js in combination with cocoon.io (Canvas+) running on an Android 5.0.1 smartphone.

**Comment by goldfire** [comment]
Have you contacted them about the issue? I would guess you'll see the exact same behavior directly using Web Audio. This sounds more like an issue with Canvas+ than with howler.js.

**Comment by Zippy1970** [comment]
No, I haven't contacted them yet, will do so. But the odd thing is that if I create a HTML5 audio object myself, it will loop perfectly. But setting a howl object to HTML5 still doesn't give me seamless loops.

**Comment by goldfire** [comment]
In your example you are using Web Audio. When you see the issue are you actually forcing `html5: true`?

**Comment by Zippy1970** [comment]
Yes, in the example I'm using Web Audio, but forcing HTML5 (by setting html5: true) doesn't make any difference.

**Comment by goldfire** [comment]
I've been searching around and it certainly appears to be an issue with Ludei's custom audio system. Going to close for now as there doesn't appear to be anything that can be done our end to solve this, but I'll re-open if anyone finds a workaround. You might also try using a different format like MP3 or WebM to see if that helps.

**Comment by JiDW** [comment]
Hi, I found this issue while checking if Howler was now working with Cocoon so I wanted to add what I know so far.

Canvas+ from Cocoon do not use the html webview audio element to play sounds, they simulate the element and play it with openAL.

I do not know how Howler deals with HTML5 audio loops, but if it appears that you stop and play again the audio element in order to do so, it won't work well with openAL because it will send the audio in a buffer, and it will start playing only when the buffer is available (it can take up to 300ms sometimes).

Using the "loop" native property create a nearly perfect loop. However it means you can only loop from the very end of the audio file to the very start.

If you have the chance to not support android devices prior to 5.0, you can use the native webview to play sounds with Webaudio or switch to Webview+ instead of Canvas+.
