### ISSUE TITLE
sound.volume() and fade()

### ISSUE THREAD

**Issue by JenGL** [goldfire/howler.js#500]
if you use sound.fade() without id then sound.volume() return 1 ignoring the fade value

**Comment by goldfire** [comment]
Which version is this referring to?

**Comment by JenGL** [comment]
2.0
Il 13/apr/2016 06:10 PM, "James Simpson" <notifications@github.com> ha
scritto:

**Comment by goldfire** [comment]
I've added one step towards this with a366eafa17b4ccd510c1ee1b6e9735ef46fecf60. However, this still only works if you don't pass in the `id`. The reason is that Web Audio is natively fading the volume for that specific sound, rather than controlling the group, so some restructuring of how the `fade` method works may be required. I'll keep looking into it when I get a chance later today or this weekend.

**Comment by goldfire** [comment]
fb58a2907580f8395128f7fa3d4b9bbf991cd25a should take care of these issues now, but please let me know if you see anything else related to fading.
