### ISSUE TITLE
promise / then functions

### ISSUE THREAD

**Issue by obiot** [goldfire/howler.js#506]
I'm not sure when exactly it happened, but I just noticed that you started using then (Promise features)
https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js#L318

if you look at the compatibility table, unless you also use a polyfill (https://github.com/stefanpenner/es6-promise), this is not really widely supported (since as part of es6)  :
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

like not at all on android devices (might explain the issue reported recently)

**Comment by goldfire** [comment]
This shouldn't be an issue because there is a check at https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js#L291 to make sure that ctx.suspend is supported. As far as I can tell, no browser/version that supports suspend/resume doesn't support promises (https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/suspend).

**Comment by obiot** [comment]
Indeed, I was just about to come back on my previous comment, as in the mean time i checked the WebAudio API, and indeed the type of `suspend` is a Promise object/interface.
