### ISSUE TITLE
Subsequent `play` invocation on the same howl instance create new instances

### ISSUE THREAD

**Issue by lifeinafolder** [goldfire/howler.js#531]
Hi,

I am working with Howler 2.0. In the following snippet, if the `play` button is clicked several times, I have noticed that several instances of the sound start playing. Is this expected behavior?

```
sound = new Howl({
  src:'http://example.com/assets/audio/background.mp3',
  loop: true,
  volume: 0.15
});

<button onclick="sound.play()">
Play
</button>
```

I have tried changing it to:
```
<button onclick="sound.stop(); sound.play();">
Play
</button>
```

This sort of fixes it but in reality what is happening is that it stops the old instance and starts playing what seems like a new instance from time 0. So the net effect is that audio starts from scratch.

What am I missing?

**Comment by goldfire** [comment]
Yes, both of those are expected behavior. If you stop a sound it is set back to the beginning. If you want to start playing from the same position you need to pause. A `Howl` is a group of sounds, and you can play as many as you want in a group. If you don't pass a `soundId` into play then a new sound instance will be created.

**Comment by goldfire** [comment]
> How do I pass soundId into play() ? @goldfire

Documented here: https://github.com/goldfire/howler.js#playspriteid

`sound.play(id)`
