### ISSUE TITLE
new src?

### ISSUE THREAD

**Issue by TaxableApples** [goldfire/howler.js#668]
I would like to either assign a new src or create new sprites with a function - but I can't figure it out... 

First I tried:
`var mysound = new Howl({`
  `src:['mysound1.ogg']`
`});`

`function changeIt(){`
  `sound.src(['mysound2.ogg']);`
`};`

This doesn't work. There is a comment from Jason Simpson on version 1 stating this was a bug and was fixed, but that was back when `urls:` was used instead of `src:` Regardless, there are further comments confirming it still didn't work.

So... then I tried creating a new howl within a function like:

`function newSprite(){`
  `var mysound = new Howl({`
  `src:['mysound2.ogg']`
  `});`
`};`

...and this doesn't work either. I am stuck. Does anyone have any ideas?

**Comment by TaxableApples** [comment]
I found a workaround to what I was trying to do.

**Comment by goldfire** [comment]
The ability to swap out sources in a specific `Howl` instance was remove din 2.0 because it never really worked correctly in 1.x and there didn't seem to be a good way to make it work correctly in all situations. Would you mind posting what your solution was so that others might find it useful? Thanks!

**Comment by TaxableApples** [comment]
No solution. I just found another way to reach a much deeper goal, this: https://github.com/goldfire/howler.js/issues/669 I created a new thread since I didn't think it would make sense here.

**Comment by gabek** [comment]
I know this was closed due to the original poster, but I'd also like to see the functionality of appending sources to the existing Howler instance.  Do you have any current workarounds, @goldfire?

**Comment by jasongrishkoff** [comment]
+1 -- I think this is relevant today in light of the HTML5 Audio throttling that Safari (and soon Chrome) are doing where new Audio events can't be fired unless the user directly initiates. Presents a pretty big problem for music websites.

According to this thread: https://github.com/scottschiller/SoundManager2/issues/178 -- the issue can be avoided by simply adding songs to the Audio element rather than creating a whole new one.

Thoughts? Have you seen this issue yet?

**Comment by jasongrishkoff** [comment]
I'm thinking #825 might be describing a similar problem.

**Comment by simply-news** [comment]
any new updates for this issue?

**Comment by fresonn** [comment]
I just started using your libraries and found out that you cannot change the source dynamically.
It's a big drawback to recreate the instance. And why can't I specify an empty src and then load it dynamically?

**Comment by duck-dev-go** [comment]
We would also like to see this functionality. We need it for our web based editor where swapping audio is a must and recreating an instance is indeed a big drawback.

**Comment by AlanGreyjoy** [comment]
![image](https://github.com/user-attachments/assets/f33e2357-6735-4155-95dd-adc418fb9bfb)
