### ISSUE TITLE
Generate a dynamic waveform like in the the Sprite example

### ISSUE THREAD

**Issue by noncototient** [goldfire/howler.js#701]
Hi @goldfire,

how do you generate a waveform like this example: https://github.com/goldfire/howler.js/tree/master/examples/sprite

I don't see anything in the example code on how it was generated.

**Comment by goldfire** [comment]
Unfortunately, I can't remember exactly how I made that. I just remember searching around for a tool that could generate waveforms from an audio file and then tweaking it in Photoshop.

**Comment by zefie** [comment]
There is a script called [WaveSurfer](https://github.com/katspaugh/wavesurfer.js).

And with some scripting one can use it with howler instead of its player. See [here](https://loops.planeptune.org/?update=5&loop=zefie_lunar&samples=6901&volume=25&debug=testing) (this is my testbed so if its broken try again later, I may be actively working on the code)
