### ISSUE TITLE
Remove event by fn, checks && id

### ISSUE THREAD

**Issue by agmcleod** [goldfire/howler.js#767]
https://github.com/goldfire/howler.js/blob/754770312ab8ca3e97cfcdf309d72bf837392906/src/howler.core.js#L1560

Was having a look over the code to see if I can remove an event just by ID, and I think I see an issue here. Given that it lists id as optional, but checks it against the event, as well as the function, I don't think one can remove an event by using the function parameter at all.

A simple fix here would be to swap it to an ||. Or one can change it to:

    if (fn === events[i].fn && (!id || id === events[i].id))

To cover what the API says it will do :)

**Comment by goldfire** [comment]
This is partially intended behavior. If you passed an ID into `on`, then you need to pass an ID into `off` because if you don't pass ID into `on` it is a different type of listener. However, I just pushed a commit that allows you to cancel like `sound.off('play', id);` instead of having to pass the function as well.
