### ISSUE TITLE
Async audio files on mobile don't play

### ISSUE THREAD

**Issue by azizantoun** [goldfire/howler.js#811]
Hello,

I'm facing an issue with audio retreived via ajax call on mobile. The sound object gets initialised but the sound doesn't play. Any workaround for that?

**Comment by jony1993** [comment]
Hello,
I've a similar problem. But only on mobile Opera (Version 42.7.2246.114996) if Wifi is not activated. If Wifi is activted everything works correct.

Config: 
preload: false, 
html5: true  (html5 has to be avtivated too, otherwise audio is not working)

Audiofile is a mp3 Audio file stored on aws, but similar problem with ogg file.

Thx in advance for your help :)

**Comment by philvoctag** [comment]
We have the same problem as jony1993 (with Opera on mobile data only). Is there anything we can do to fix it? Any workarounds?

**Comment by azizantoun** [comment]
@jony1993  How were you able to call Howlr in an async callback? Creating the object in a callback isn't loading on mobile.

**Comment by jony1993** [comment]
@azizantoun 
Is the audio not loaded via XMLHttpRequest by default?

Look at the page https://www.lokobox.de/

There I implemented the basic Howler like:

    function play(){
            sound = new Howl({
                src: ['xxx.mp3'],
                preload:false,
                html5: true

      });

      sound.load();
      sound.play();

Audio is working on all devices. But only on opera mobile (if wifi deactivated, mobile data activated) the sound is not playing.

**Comment by azizantoun** [comment]
What I'm trying to do is something like this.

$.ajax
({
  type: "GET",
  url: "ajax.php",
  data: dataString,
  success: function(data)
  {
      sound = new Howl({
            src: ['data.song.mp3'],
            preload:false,
            html5: true
  }
});

This works perfectly on desktop. But doesn't on mobile

**Comment by jony1993** [comment]
Why do you want to load the file with ajax?
Is the file not loaded by Howler?

**Comment by azizantoun** [comment]
My mp3 files are stored on S3, can only retrieve them through api calls. Which is making playing a sound on mobile impossible.

**Comment by jony1993** [comment]
Do you have any example code?

**Comment by azizantoun** [comment]
It's the one I sent previsouly. That's the logic I'm trying to use.

Call an API --> GET the mp3 file --> Init Howlr and try to play sound. 
Plays on desktop, doesn't on mobile due to mobile user interaction restriction.

$.ajax
({
type: "GET",
url: "ajax.php",
data: dataString,
success: function(data)
{
sound = new Howl({
src: ['data.song.mp3'],
preload:false,
html5: true
}
});

PS: Once the file is loaded pressing on pause then resume plays the sounds since the mp3 files is now ready.

**Comment by tabe1hands** [comment]
I have the same problem with Safari on iOS 10.3. To avoid the problem, I added `async: false` option to `$.ajax` as workaround.

However, it's just workaround.

**Comment by goldfire** [comment]
This is because audio needs to be unlocked before loading/playing from within a user action (https://github.com/goldfire/howler.js#mobile-playback). You'll probably want to add a button on loading of your app that plays a silent sound to unlock it (howler tries to do this automatically, but obviously doesn't add a button for you).
