### ISSUE TITLE
IE11 Sprite, sounds play through to next sound

### ISSUE THREAD

**Issue by shawnbissell** [goldfire/howler.js#857]
When playing an audio sprite in IE 11 the sound does not stop at the end duration and just plays through to the next sound. 

The problem can easily be seen on the demo page:
https://howlerjs.com/#sprite
Just play one of the sounds, and you can hear and even see the next sound (and the rest) be played.

IE Version: 11.1000.161710.0
IE Update Version: 11.0.41
Windows 10 Pro 64-bit 
Version 1703
OS Build 16170.1000

**Comment by shawnbissell** [comment]
I've traced the problem to the _ended method which seems to always exit out early in IE and never hits the stop method at the end. If i comment out the following code it fixes the problem
```
      // If we are using IE and there was network latency we may be clipping
      // audio before it completes playing. Lets check the node to make sure it
      // believes it has completed, before ending the playback.
      if (!self._webAudio && sound._node && !sound._node.paused) {
        setTimeout(self._ended.bind(self, sound), 100);
        return self;
      }
```
I'm not sure what the correct fix is ...

**Comment by shawnbissell** [comment]
Turns out there is an open PR with a proper fix for this https://github.com/goldfire/howler.js/pull/829
I've tested it out and it seems to work fine for my project.

**Comment by funkeh** [comment]
This issue is still present in IE11. As far as I can tell, playing many sounds from the same audio sprite at once can trigger the issue in specific circumstances.

I've replicated this issue on the Howler.js website, by quickly clicking "beat" a few times, "two" a few times and then "one" a few times: https://www.youtube.com/watch?v=vTGrXS8DY0E

OS: Windows 10
IE: 11.765.17134.0
Pointing device: Mouse
