### ISSUE TITLE
FireFox stream stoped

### ISSUE THREAD

**Issue by amirping** [goldfire/howler.js#883]
i use howler to play stream from URL . it work correctly on chrome , but with Firefox the stream auto stop after few seconds ( about 20s ) . 
```
  this.sound = new Howl({
      src: [streamUrl],
      html5: true,
      autoplay : true, // try to fix 
      format: ['mp3'] // try to fix 
});
```
on chrome it work even without the autoplay and the format option .
Firefox Quantom 57.0.2

**Comment by asaivan** [comment]
I have had the same issue.  Trying to get it working on FF 57.  Stops after 1 second with no errors.

**Comment by roks0n** [comment]
Having the same issue, these are my settings:
```
radio = new Howl({
    src: stations[currentStation].stream,
    html5: true,
    format: ['mp3'],
    volume: volume,
});
radio.play();
```

**Comment by trvbr** [comment]
This is happening for us as well.

Test it here: https://jsfiddle.net/trvbr/guw1uu1L

SoundManager2 works in the same Firefox environment. Check out his (Scott Schiller's) code for pointers? Maybe there is a hack in there that fixes it.

**Comment by amirping** [comment]
@roks0n yes i noticed that , i think it's problem with buffer or some think like that since the `onend ` function is called when the media end .

**Comment by goldfire** [comment]
Interesting, I wonder when this change was made in Firefox. Unless I'm missing something, it looks like the only way to fix this is to listen to the `curationchange` event and re-create the ended timer with the difference in duration added on. This feels really hacky though. Has anyone found any other way to detect if a stream is being played in Firefox (the duration of Infinity was being relied upon previously)?

**Comment by AlteranAncient** [comment]
I've just been bitten by this as well. I made the leap from Chrome to Quantum a few weeks ago, and I've noticed some odd behaviour specific to the current version of Firefox:

- (On latest Howler), Firefox will stop playing any stream after a short amount of time. SM2 behaves for MP3s, but randomly cuts-off when playing OGG streams.
- (In SoundManager2), Firefox will randomly decide to stop playing Vorbis or Opus streams in .ogg wrappers.

I realise you're probably not that interested in SM2 itself, but I think that it is probably helpful to know that Firefox may not be handling streams with OGG extensions correctly - and that it might not be specific to Howler.

**Comment by ntavelis** [comment]
I have the same issue, using the version 2.0.5 solves this problem. So a change must have been made after this version.

**Comment by kenger** [comment]
Yeah, I can confirm that works. Versions 2.0.7 and 2.0.8 have the problem, i dont know for version 2.0.6 but version 2.0.5 is working.

**Comment by ntavelis** [comment]
2.0.6 has the same issue.

**Comment by mmavko** [comment]
same issue here. jsfiddle: https://jsfiddle.net/guw1uu1L/3/

playback stops after some 5 seconds (Chrome 64, Mac OS, Ubuntu).

**Comment by goldfire** [comment]
The reason it "works" in 2.0.5 is because it is broken. The ended event is still getting fired, but since the sound is still playing, howler goes into an infinite timeout loop checking for it to be over. The addition of a time check relative to the reported duration causes it to end at the correct time (https://github.com/goldfire/howler.js/commit/ee3d0aed9bc9879742b9cc4bac069c9b494f7fa7). Since it is a stream, the duration should be reported as Infinity, but for some reason, Firefox is reporting an incorrect duration value.

**Comment by kenger** [comment]
Usage of an html5 audio element show the strange behavior of Firefox. An audio element with my live stream source has an increasing duration instead of a positive Infinite as specified by the html5 spec.

I dont know if this is a problem with my server (ICEcast) metadata or Firefox. I dont understand how firefox should know if an mp3 is a live or not.
