### ISSUE TITLE
html5 true very unstable on mobile

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#953]
I was having big problems on  mobile with the sounds  sometimes starting, sometimes not, almost random, until I switched from html5=true,  to false, and now its all stable,
so html5 audio doesnt seem to work well on mobile phones, on desktop yes, but not on mobile,

previously I had  to use html5 audio because of CORS crossdomain issues, but  now  I made a php proxy that allows me to use web audio again, 

in any case, its a pity that html5 audio on mobile is so unstable

**Comment by TxAg12** [comment]
Go complain to the iOS, Google, and other browser development teams who think this is how the internet should work. This isn't because of howler. This is because web browser developers are intentionally trying to prohibit methods of playing audio.

While some individuals simply stop visiting websites that have annoying or malicious sounds or videos, some others decide to break the internet because of it.

Use `html5:false`. Yes, it sucks, but they haven't killed WebAudio yet.

**Comment by javismiles** [comment]
I totally and 100% agree with you, it's very frustrating what they are doing, yes it was my intention to always use html5:false but because of Cors I couldn't in this case; fortunately I found a way to make it work using a php proxy and now I can use html5:false and webaudio which is great, thank u for your quick feedback and support, all best

**Comment by TxAg12** [comment]
I saw your other thread as well. I am going to test that approach sometime.
