### ISSUE TITLE
Howler doesn't working play with codec m3u8 (streaming)

### ISSUE THREAD

**Issue by cnttech** [goldfire/howler.js#968]
Hi all,

I'm using howler play music with  file streaming .m3u8. But it's not working and error with alert 'No codec support for selected audio sources.'

My code is here:

```
sound = data.howl = new Howl({

            src: [data.file],
            html5: true,
            autoplay:false,
            format: ['m3u8','mp3']
});
```
i need any help to play it.

Thank you for any help.  
Best regards,

**Comment by Torx** [comment]
Hello i have the same problem on internet explorer 11 for a client.

computer 1: WIN 7 N (client computer)
error message when play mp3: 4
error message when play wav: No codec support for selected audio sources
second error for same wav: 4

computer 2: WIN 10 PRO (my computer at work for test)
mp3: no problem the sound play
wav: No codec support for selected audio sources
second error for same wav: 4

computer 3: WIN 7 N (virtual machine for test at work)
mp3: no problem the sound play
wav: No codec support for selected audio sources
second error for same wav: 4

computer 4: WIN 10 N (team mate computer at work for test)
mp3: No audio support
wav: No audio support

For WIN x N, a solution is to install the Media Features Pack: https://support.microsoft.com/fr-fr/help/3145500/media-feature-pack-list-for-windows-n-editions

But for my client it is impossible because he have 100 000 computers ...

So i have 3 questions:
What is the error message "4" ?
How to fix on WIN x N Internet Explorer 11 without install Media Features Pack ?
Is it possible to send mp3 codec in web site ?

Best regards

**Comment by Torx** [comment]
To see what audio format Howler can play on your computer/browser launch this javascript code line in your console:

console.log(Howler._codecs);

**Comment by muhammad-Haris-1** [comment]
m3u8 is not supported by Howler
